name             'rbenv'
maintainer       'Álvaro Faúndez'
maintainer_email 'alvaro@faundez.net'
license          'All rights reserved'
description      'Installs/Configures rbenv'
long_description 'Installs/Configures rbenv'
version          '1.1.4'

depends 'apt'
depends 'build-essential'
depends 'git'
